[package]
name = "selfinstaller"
version = "0.1.0"
edition = "2021"

[dependencies]
eyre = "0.6.5"
owo-colors = "3.2.0"
tempfile = "3.2.0"
thiserror = "1.0.26"

[target.'cfg(windows)'.dependencies]
mslnk = "0.1.6"

[dev-dependencies]
argh = "0.1.6"
tempfile = "3.2.0"
