[repositories.test]
url = "local:target/test-repo"

[repositories.test.password]
toml = "example/test-secret.toml"
key = "test-password"

[backups.test]
repository = "test"
path = "."
exclude_caches = true
excludes = ["target"]

[[backups.test.triggers]]
cron = "* * * * *"

[backups.target]
repository = "test"
path = "target"
exclude_caches = true
excludes = ["test-repo"]

[[backups.target.triggers]]
cron = "5 * * * *"
