[repositories.test]
url = "local:target/test-repo"

[repositories.test.password]
env_var = "TEST_PASSWORD"

[backups.test]
repository = "test"
path = "."
exclude_caches = true
exclude = ["target"]

[[backups.test.triggers]]
cron = "* * * * *"
