[repositories.test]
url = "local:target/test-repo"

[repositories.test.password]
toml = "example/test-secret.toml"
key = "test-password"

[backups.test]
repository = "test"
path = "."
exclude_caches = true
excludes = ["target"]

[[backups.test.triggers]]
at = "0:00 and 6:00 and 12:00 and 18:00"
every = "day"
