image: registry.gitlab.com/fkrull/cirrus/ci-tools:latest

variables:
  STORAGE_DRIVER: vfs
  BUILDAH_ISOLATION: chroot
  CARGO_HOME: ${CI_PROJECT_DIR}/cargo
  SCCACHE_DIR: ${CI_PROJECT_DIR}/sccache
  RUSTC_WRAPPER: sccache

cache:
  paths:
    - cargo/
    - sccache/

include:
  - template: 'Workflows/Branch-Pipelines.gitlab-ci.yml'

stages:
  - tools
  - test
  - package
  - manifest-list
  - publish


# ----
tools:ci-tools-image:
  stage: tools
  image: fedora:33
  when: manual
  before_script:
    - dnf install -y buildah
  script:
    - buildah build-using-dockerfile
      -f .ci/tools.Containerfile
      --creds $CI_REGISTRY_USER:$CI_REGISTRY_PASSWORD
      -t docker://registry.gitlab.com/fkrull/cirrus/ci-tools:latest
      .ci

test:
  stage: test
  script:
    - cargo fmt -- --check
    - sccache --start-server
    - cargo test --workspace --all-features
    - sccache --show-stats

# package steps
appx:x86_64:
  extends: .appx
  stage: package
  rules:
    - if: $CI_COMMIT_TAG
      when: always
    - when: manual
  variables:
    TARGET: x86_64-pc-windows-msvc
    APPX_VERSION: ${CI_COMMIT_REF_NAME}

server:linux:x86_64:
  extends: .server
  stage: package
  rules:
    - if: $CI_COMMIT_TAG
      when: always
    - when: manual
  variables:
    TARGET: x86_64-unknown-linux-musl
    TAG: ${CI_COMMIT_REF_NAME}-linux-amd64

server:linux:armv7:
  extends: .server
  stage: package
  rules:
    - if: $CI_COMMIT_TAG
      when: always
    - when: manual
  variables:
    TARGET: armv7-unknown-linux-musleabihf
    QEMU_BINARY: /usr/bin/qemu-arm-static
    TAG: ${CI_COMMIT_REF_NAME}-linux-arm32v7

server:manifest-list:
  stage: manifest-list
  needs: [ "server:linux:x86_64" ,"server:linux:armv7" ]
  script:
    - buildah manifest create cirrus-manifest-list
      docker://registry.gitlab.com/fkrull/cirrus/server:${CI_COMMIT_REF_NAME}-linux-amd64
      docker://registry.gitlab.com/fkrull/cirrus/server:${CI_COMMIT_REF_NAME}-linux-arm32v7
    - buildah manifest push
      --creds $CI_REGISTRY_USER:$CI_REGISTRY_PASSWORD
      cirrus-manifest-list
      docker://registry.gitlab.com/fkrull/cirrus/server:${CI_COMMIT_REF_NAME}

# publish
publish:server:
  stage: publish
  needs: [ "server:manifest-list" ]
  rules:
    - if: $CI_COMMIT_TAG
      when: always
  script:
    - skopeo copy
      --dest-creds $CI_REGISTRY_USER:$CI_REGISTRY_PASSWORD
      docker://registry.gitlab.com/fkrull/cirrus/server:${CI_COMMIT_REF_NAME}
      docker://registry.gitlab.com/fkrull/cirrus/server:latest


# ----
# build Linux container image
.server:
  before_script:
    - rustup target add ${TARGET}
  script:
    - sccache --start-server
    - cargo run -p package --bin server --
      --target ${TARGET}
      --qemu-binary "${QEMU_BINARY}"
    - sccache --show-stats
    - buildah push
      --creds $CI_REGISTRY_USER:$CI_REGISTRY_PASSWORD
      cirrus-server-image
      docker://registry.gitlab.com/fkrull/cirrus/server:${TAG}

# build Windows appx package
.appx:
  tags:
    - shared-windows
    - windows
    - windows-1809
  before_script:
    - choco install -y sccache
    - Invoke-WebRequest https://win.rustup.rs/x86_64 -OutFile rustup-init.exe
    - $env:CARGO_HOME = "$env:USERPROFILE/.cargo"
    - ./rustup-init.exe -y --default-host="$TARGET" --default-toolchain=stable --profile=minimal
    - $env:CARGO_HOME = "${CI_PROJECT_DIR}/cargo"
    - $env:PATH += ";$env:USERPROFILE/.cargo/bin"

    - $sdkPath = (Get-ItemProperty "HKLM:\Software\Microsoft\Windows Kits\Installed Roots").KitsRoot10
    - $latest = Get-ChildItem "$sdkPath\bin"
      | Foreach-Object {$_.Name}
      | Select-String "10.0"
      | Sort-Object
      | Select-Object -Last 1
    - $env:PATH += ";$sdkPath\bin\$latest\x64"
  script:
    - $thumbprint = package\windows\import-base64-certificate.ps1 Cert:\LocalMachine\My
    - sccache --start-server
    - cargo run -p package --bin appx --
      --target ${TARGET}
      --version ${APPX_VERSION}
      --cert-thumbprint $thumbprint
      --use-system-cert-store
    - sccache --show-stats
  artifacts:
    paths:
      - target/*.appx
      - target/*.appinstaller
    expire_in: 1 day
