image: registry.gitlab.com/fkrull/cirrus/ci-tools:latest

variables:
  STORAGE_DRIVER: vfs
  BUILDAH_ISOLATION: chroot
  CARGO_HOME: ${CI_PROJECT_DIR}/cargo
  SCCACHE_DIR: ${CI_PROJECT_DIR}/sccache
  RUSTC_WRAPPER: sccache

cache:
  paths:
    - cargo/
    - sccache/

include:
  - template: 'Workflows/Branch-Pipelines.gitlab-ci.yml'

stages:
  - tools
  - test
  - package
  - manifest
  - publish


# ----
tools:ci-tools-image:
  stage: tools
  image: fedora:33
  when: manual
  before_script:
    - dnf install -y buildah
  script:
    - buildah build-using-dockerfile
      -t ci-tools
      build-scripts/ci-tools
    - buildah push
      --creds $CI_REGISTRY_USER:$CI_REGISTRY_PASSWORD
      ci-tools
      docker://registry.gitlab.com/fkrull/cirrus/ci-tools:latest

build-version:
  stage: test
  script:
    - mkdir -p target
    - sccache --start-server
    - cargo run -p build-scripts --bin get-build-version > target/build-version
    - sccache --show-stats
    - cat target/build-version
  artifacts:
    reports:
      dotenv: target/build-version
    expire_in: 1 day

test:
  stage: test
  script:
    - cargo fmt -- --check
    - sccache --start-server
    - cargo test --workspace --all-features
    - sccache --show-stats

# package steps
desktop:linux:x86_64:
  extends: .desktop
  stage: package
  variables:
    OS: linux
    ARCH: x86_64
    TARGET: x86_64-unknown-linux-gnu
    PACKAGE_TYPE: tar.bz2
    PACKAGE_RUSTFLAGS: -Clinker=x86_64-linux-gnu-gcc -L/lib/x86_64-linux-gnu -L/usr/lib/x86_64-linux-gnu

desktop:linux:armv7:
  extends: .desktop
  stage: package
  variables:
    OS: linux
    ARCH: arm
    TARGET: armv7-unknown-linux-gnueabihf
    PACKAGE_TYPE: tar.bz2
    PACKAGE_RUSTFLAGS: -Clinker=arm-linux-gnueabihf-gcc -L/lib/arm-linux-gnueabihf -L/usr/lib/arm-linux-gnueabihf

desktop:linux:aarch64:
  extends: .desktop
  stage: package
  variables:
    OS: linux
    ARCH: aarch64
    TARGET: aarch64-unknown-linux-gnu
    PACKAGE_TYPE: tar.bz2
    PACKAGE_RUSTFLAGS: -Clinker=aarch64-linux-gnu-gcc -L/lib/aarch64-linux-gnu -L/usr/lib/aarch64-linux-gnu

desktop:windows:x86_64:
  extends: .desktop
  stage: package
  variables:
    OS: windows
    ARCH: x86_64
    TARGET: x86_64-pc-windows-gnu
    PACKAGE_TYPE: zip

server:linux:x86_64:
  extends: .server
  stage: package
  variables:
    TARGET: x86_64-unknown-linux-musl
    TAG: ${CIRRUS_IMAGE_TAG}-linux-amd64

server:linux:armv7:
  extends: .server
  stage: package
  variables:
    TARGET: armv7-unknown-linux-musleabihf
    QEMU_BINARY: /usr/bin/qemu-arm-static
    TAG: ${CIRRUS_IMAGE_TAG}-linux-arm32v7

server:linux:aarch64:
  extends: .server
  stage: package
  variables:
    TARGET: aarch64-unknown-linux-musl
    QEMU_BINARY: /usr/bin/qemu-aarch64-static
    TAG: ${CIRRUS_IMAGE_TAG}-linux-arm64v8

# package manifests
server:manifest:
  stage: manifest
  needs:
    - build-version
    - server:linux:x86_64
    - server:linux:armv7
    - server:linux:aarch64
  script:
    - buildah manifest create cirrus-manifest-list
      docker://registry.gitlab.com/fkrull/cirrus/server:${CIRRUS_IMAGE_TAG}-linux-amd64
      docker://registry.gitlab.com/fkrull/cirrus/server:${CIRRUS_IMAGE_TAG}-linux-arm32v7
      docker://registry.gitlab.com/fkrull/cirrus/server:${CIRRUS_IMAGE_TAG}-linux-arm64v8
    - buildah manifest push
      --creds $CI_REGISTRY_USER:$CI_REGISTRY_PASSWORD
      cirrus-manifest-list
      docker://registry.gitlab.com/fkrull/cirrus/server:${CIRRUS_IMAGE_TAG}

desktop:manifest:
  stage: manifest
  needs:
    - build-version
    - desktop:linux:x86_64
    - desktop:linux:armv7
    - desktop:linux:aarch64
    - desktop:windows:x86_64
  script:
    - cargo run -p build-scripts --bin finalize-manifest --
      --url-pattern ${CI_PROJECT_URL}/-/jobs/${CI_JOB_ID}/artifacts/raw/public/__FILENAME__
      public
  artifacts:
    paths:
      - public
    expire_in: 1 day

# publish
server:publish:
  stage: publish
  needs:
    - server:manifest
  rules:
    - if: $CI_COMMIT_TAG
      when: always
  script:
    - skopeo copy
      --all
      --dest-creds $CI_REGISTRY_USER:$CI_REGISTRY_PASSWORD
      docker://registry.gitlab.com/fkrull/cirrus/server:${CIRRUS_IMAGE_TAG}
      docker://registry.gitlab.com/fkrull/cirrus/server:latest

pages:
  stage: publish
  needs:
    - desktop:manifest
  rules:
    - if: $CI_COMMIT_TAG
      when: always
  script:
    - cp public/manifest.json latest.json
    - rm public/*
    - cp latest.json public/latest.json
  artifacts:
    paths:
      - public


# ----
# build desktop binary package
.desktop:
  before_script:
    - rustup target add ${TARGET}
  script:
    - sccache --start-server
    - cargo run -p build-scripts --bin binaries --
      --target ${TARGET}
      --features desktop
      --version ${CIRRUS_VERSION}
      --rustflags "${PACKAGE_RUSTFLAGS}"
      ${BINARIES_ARGS}
    - cargo run -p build-scripts --bin package-generic --
      --os ${OS}
      --arch ${ARCH}
      --build-type desktop
      --version ${CIRRUS_VERSION}
      --pkg-type ${PACKAGE_TYPE}
      target/binaries
    - sccache --show-stats
  artifacts:
    paths:
      - public
    expire_in: 1 day

# build Linux container image
.server:
  before_script:
    - rustup target add ${TARGET}
  script:
    - sccache --start-server
    - cargo run -p build-scripts --bin binaries --
      --target ${TARGET}
      --features ""
      --version ${CIRRUS_VERSION}
      --rustflags "-Clinker=rust-lld"
    - cargo run -p build-scripts --bin package-server --
      --target ${TARGET}
      --qemu-binary "${QEMU_BINARY}"
      target/binaries
    - sccache --show-stats
    - buildah push
      --creds $CI_REGISTRY_USER:$CI_REGISTRY_PASSWORD
      cirrus-server-image
      docker://registry.gitlab.com/fkrull/cirrus/server:${TAG}
