[package]
name = "cirrus"
version = "0.1.0"
authors = ["Felix Krull <f_krull@gmx.de>"]
edition = "2018"

[workspace]
members = [
    "cirrus-actor",
    "cirrus-core",
    "cirrus-daemon",
    "cirrus-desktop-ui",
    "cirrus-windows-wrapper",
    "build-scripts",
]

[dependencies]
cirrus-core = { path = "cirrus-core" }
cirrus-actor = { path = "cirrus-actor" }
cirrus-daemon = { path = "cirrus-daemon" }
cirrus-desktop-ui = { path = "cirrus-desktop-ui", optional = true }
eyre = "0.6.1"
clap = "3.0.0-beta.2"
hostname = "0.3.1"
log = "0.4.8"
opener = { version = "0.4.1", optional = true }
rpassword = "5.0.0"
termcolor = "1.1.0"
toml = "0.5.6"
color-eyre = "0.5.6"
dirs-next = "2.0.0"

[dependencies.log4rs]
version = "1.0.0"
default-features = false
features = ["console_appender"]

[dependencies.tokio]
version = "1.0.0"
features = ["macros", "signal", "rt-multi-thread"]

[features]
default = []

# desktop features
desktop-commands = ["opener"]
desktop = ["desktop-commands", "cirrus-core/keyring", "cirrus-desktop-ui"]
