[package]
name = "cirrus"
version = "0.1.0"
authors = ["Felix Krull <f_krull@gmx.de>"]
edition = "2018"

[workspace]
members = [
    "cirrus-core",
    "cirrus-daemon",
    "cirrus-web",
]

[dependencies]
cirrus-core = { path = "cirrus-core" }
cirrus-daemon = { path = "cirrus-daemon" }
cirrus-web = { path = "cirrus-web" }
anyhow = "1.0.30"
clap = "2.33.1"
dirs = "2.0.2"
env_logger = "0.7.1"
log = "0.4.8"
rpassword = "4.0.5"
termcolor = "1.1.0"
toml = "0.5.6"

[dependencies.tokio]
version = "0.2.22"
features = ["fs", "macros"]

[features]
default = ["os-keyring"]
os-keyring = ["cirrus-core/os-keyring"]
