[package]
name = "restic-controller"
version = "0.1.0"
authors = ["Felix Krull <f_krull@gmx.de>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cron-parser = "0.7.4"
rocket = "0.4.4"
serde = { version = "1.0.110", features = ["derive"] }
toml = "0.5.6"

[dev-dependencies]
maplit = "1.0.2"
