[package]
name = "cirrus"
version = "0.1.0"
authors = ["Felix Krull <f_krull@gmx.de>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.30"
chrono = "0.4.11"
cron-parser = "0.7.4"
dirs = "2.0.2"
env_logger = "0.7.1"
log = "0.4.8"
rocket = "0.4.4"
serde = { version = "1.0.110", features = ["derive"] }
toml = "0.5.6"
webbrowser = { version = "0.5.2", optional = true }

[features]
default = ["desktop-integration"]
desktop-integration = ["webbrowser"]

[dev-dependencies]
maplit = "1.0.2"
serde_json = "1.0.53"
