[package]
name = "cirrus"
version = "0.1.0"
authors = ["Felix Krull <f_krull@gmx.de>"]
edition = "2018"

[workspace]
members = [
    "cirrus-actor",
    "cirrus-core",
    "cirrus-daemon",
    "cirrus-web",
]

[dependencies]
cirrus-core = { path = "cirrus-core" }
cirrus-daemon = { path = "cirrus-daemon" }
eyre = "0.6.1"
clap = "2.33.1"
dirs = "2.0.2"
env_logger = "0.7.1"
hostname = "0.3.1"
log = "0.4.8"
opener = { version = "0.4.1", optional = true }
rpassword = "4.0.5"
termcolor = "1.1.0"
toml = "0.5.6"
color-eyre = "0.5.6"

[dependencies.tokio]
version = "0.2.22"
features = ["fs", "macros", "signal"]

[features]
default = []

# desktop features
desktop-integration = ["opener", "cirrus-core/keyring"]

# release features
#bundled-assets = ["cirrus-web/bundled-assets"]
