[package]
name = "restic-bin-build"
version = "0.1.0"
authors = ["Felix Krull <f_krull@gmx.de>"]
edition = "2018"


[dependencies]
bzip2 = "0.4.1"
eyre = "0.6.5"
hex = "0.4.2"
sha2 = "0.9.2"
tempfile = "3.1.0"
ureq = "2.0.1"
zip = "0.5.8"
