[package]
name = "cirrus-self"
version = "0.1.0"
edition = "2018"

[dependencies]
clap = "3.0.5"
eyre = "0.6.5"
selfinstaller = { path = "../selfinstaller" }

[target.'cfg(windows)'.dependencies]
windirs = "1.0.1"

[target.'cfg(not(windows))'.dependencies]
dirs-next = "2.0.0"
