[package]
name = "cirrus-core"
version = "0.1.0"
authors = ["Felix Krull <f_krull@gmx.de>"]
edition = "2018"

[dependencies]
eyre = "0.6.1"
chrono = "0.4.11"
cron-parser = "0.7.4"
futures = "0.3.5"
keyring = { version = "0.10.1", optional = true }
log = "0.4.8"
serde = { version = "1.0.110", features = ["derive"] }
thiserror = "1.0.20"
toml = "0.5.6"
tokio-stream = { version = "0.1.6", features = ["io-util"] }
pin-project = "1.0.7"

[dependencies.tokio]
version = "1.0.0"
features = ["fs", "process", "io-util", "macros"]

[target.'cfg(windows)'.dependencies]
winapi = { version = "0.3.9", features = ["winbase"] }
atty = "0.2.14"

[dev-dependencies]
maplit = "1.0.2"
serde_json = "1.0.53"
