name: rust
description: "Install Rust toolchain, with caching"

inputs:
  rust:
    required: false
    description: "Rust toolchain, e.g. 'stable' or 'nightly'"
    default: stable
  targets:
    required: false
    description: Additional rustup targets to install
    default: ''
  components:
    required: false
    description: Additional components to install via rustup, e.g. clippy
    default: ''
  cache-key:
    required: false
    description: Extra key to resolve cache
    default: ''

runs:
  using: composite
  steps:
    - name: Install Rust
      run: |
        rustup toolchain install ${{ inputs.rust }} --profile minimal --component ${{ inputs.components }} --target ${{ inputs.targets }} --no-self-update
        rustup default ${{ inputs.rust }}
      shell: bash
    - name: Set up Rust cache
      uses: Swatinem/rust-cache@v2
      with:
        shared-key: ${{ inputs.cache-key }}

    - name: "Set environment variables used by toolchain"
      run: |
        echo CARGO_TERM_COLOR=always >> $GITHUB_ENV
        echo CARGO_INCREMENTAL=0 >> $GITHUB_ENV
        echo RUST_BACKTRACE=1 >> $GITHUB_ENV
        
        rustc --version --verbose
      shell: bash
