name: rust
description: Install Rust toolchain with caching

inputs:
  targets:
    required: false
    description: Comma-separated string of additional targets to install e.g. wasm32-unknown-unknown
  components:
    required: false
    description: Comma-separated string of additional components to install e.g. clippy, rustfmt
  cache-key:
    required: false
    description: Extra key to resolve cache
    default: ''

runs:
  using: composite
  steps:
    - uses: dtolnay/rust-toolchain@stable
      with:
        targets: ${{ inputs.targets }}
        components: ${{ inputs.components }}
    - uses: Swatinem/rust-cache@v2
      with:
        shared-key: ${{ inputs.cache-key }}
