[package]
name = "cirrus-daemon"
version = "0.1.0"
authors = ["Felix Krull <f_krull@gmx.de>"]
edition = "2018"

[dependencies]
cirrus-actor = { path = "../cirrus-actor" }
cirrus-core = { path = "../cirrus-core" }
async-trait = "0.1.41"
futures = "0.3.6"
eyre = "0.6.1"
chrono = "0.4.19"
uuid = { version = "0.8.1", features = ["v4"] }
notify = "5.0.0-pre.6"
tracing = "0.1.23"
tracing-futures = "0.2.4"

[dependencies.tokio]
version = "1.0.0"
features = ["time"]
