[package]
name = "cirrus-daemon"
version = "0.1.0"
authors = ["Felix Krull <f_krull@gmx.de>"]
edition = "2018"

[dependencies]
cirrus-actor = { path = "../cirrus-actor" }
cirrus-core = { path = "../cirrus-core" }
async-trait = "0.1.41"
log = "0.4.8"
futures = "0.3.6"
