[package]
name = "cirrus-daemon"
version = "0.1.0"
authors = ["Felix Krull <f_krull@gmx.de>"]
edition = "2018"

[dependencies]
cirrus-core = { path = "../cirrus-core" }
anyhow = "1.0.30"
futures = "0.3.5"
log = "0.4.8"
async-trait = "0.1.41"
thiserror = "1.0.21"

[dependencies.tokio]
version = "0.2.22"
features = ["sync"]
