[package]
name = "build-scripts"
version = "0.1.0"
authors = ["Felix Krull <f_krull@gmx.de>"]
edition = "2018"

[dependencies]
argh = "0.1.4"
eyre = "0.6.3"
restic-bin = { path = "../restic-bin", features = ["download"] }
tempfile = "3.2.0"
xshell = "0.1.8"
