[package]
name = "snisni"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
zbus = { version = "3.4.0", default-features = false }

[dev-dependencies]
tokio = { version = "1.21.2", features = ["rt", "macros"] }
zbus = { version = "3.4.0", default-features = false, features = ["tokio"] }
