name: Build
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  fmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          components: rustfmt
      - name: Run cargo fmt
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check

  test:
    strategy:
      fail-fast: true
      matrix:
        platform: [windows-latest, ubuntu-latest]
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
      - name: Install libdbus-1-dev
        if: ${{ matrix.platform == 'ubuntu-latest' }}
        run: sudo apt-get install -y libdbus-1-dev
      - uses: Swatinem/rust-cache@v2
        with:
          key: ${{matrix.platform }}
      - name: Run cargo test
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --workspace

  build-scripts:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
      - uses: Swatinem/rust-cache@v2
      - name: Build build-scripts
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --package build-scripts
      - uses: actions/upload-artifact@v3
        with:
          name: build-scripts
          path: target/debug/build-scripts

  version:
    runs-on: ubuntu-latest
    needs: [ build-scripts ]
    outputs:
      VERSION: ${{ steps.getCirrusVersion.outputs.VERSION }}
      BUILD_STRING: ${{ steps.getCirrusVersion.outputs.BUILD_STRING }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/download-artifact@v3
        with:
          name: build-scripts
      - name: Get cirrus version
        id: getCirrusVersion
        run: ./build-scripts get-version >> "$GITHUB_OUTPUT"
      - name: Print versions
        run: |
          echo VERSION=${{ steps.getCirrusVersion.outputs.VERSION }}
          echo BUILD_STRING=${{ steps.getCirrusVersion.outputs.BUILD_STRING }}

  package:
    # older Ubuntu version because of glibc compatibility
    runs-on: ubuntu-20.04
    needs:
      - build-scripts
      - version
    strategy:
      fail-fast: true
      matrix:
        target:
          - x86_64-unknown-linux-gnu
          - armv7-unknown-linux-gnueabihf
          - aarch64-unknown-linux-gnu
          - x86_64-pc-windows-gnu
    steps:
      - uses: actions/checkout@v3
      - uses: actions/download-artifact@v3
        with:
          name: build-scripts
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: ${{ matrix.target }}
          profile: minimal
      - uses: actions/setup-go@v3
        with:
          go-version: '^1.19'
          cache: true
          cache-dependency-path: vendor/restic/go.sum
      - name: Install ninja and cross-compiling toolchains
        run: sudo apt-get install -y ninja-build gcc-mingw-w64-x86-64 gcc-aarch64-linux-gnu gcc-arm-linux-gnueabihf
      - name: Install meson
        run: sudo pip3 install meson
      - uses: Swatinem/rust-cache@v2
        with:
          key: ${{matrix.target }}
      - name: Build package
        run: >
          ./build-scripts package 
          --version ${{ needs.version.outputs.VERSION }}
          --build-string ${{ needs.version.outputs.BUILD_STRING }}
          --target ${{ matrix.target }}
          --features bundled-restic-support
          --static-dbus
          --build-restic
      - uses: actions/upload-artifact@v3
        with:
          name: cirrus_${{ matrix.target }}
          path: public/*

  container-image:
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'push' }}
    needs:
      - build-scripts
      - version
      - package
    strategy:
      fail-fast: true
      matrix:
        target:
          - x86_64-unknown-linux-gnu
          - armv7-unknown-linux-gnueabihf
          - aarch64-unknown-linux-gnu
        include:
          - target: x86_64-unknown-linux-gnu
            tag: linux-amd64
          - target: armv7-unknown-linux-gnueabihf
            tag: linux-arm32v7
          - target: aarch64-unknown-linux-gnu
            tag: linux-arm64v8
    env:
      TAG: ghcr.io/${{ github.repository_owner }}/cirrus:${{ needs.version.outputs.VERSION }}-${{ needs.version.outputs.BUILD_STRING }}-${{ matrix.tag }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/download-artifact@v3
        with:
          name: build-scripts
      - uses: actions/download-artifact@v3
        with:
          name: cirrus_${{ matrix.target }}
      - uses: docker/setup-qemu-action@v2
      - name: Build container image
        run: >
          ./build-scripts container-image
          --binaries-tar cirrus_${{ matrix.target }}.tar.xz
          --tag ${{ env.TAG }}
          --target ${{ matrix.target }}
      - name: Push image
        uses: redhat-actions/push-to-registry@v2
        with:
          tags: ${{ env.TAG }}
          username: ${{ github.actor }}
          password: ${{ github.token }}
          registry: ghcr.io/${{ github.repository_owner }}
