name: Build
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  go-version: '^1.19.0'
  zig-version: '0.9.1'

jobs:
  fmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          components: rustfmt
      - name: Run cargo fmt
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check

  clippy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          components: clippy
      - uses: Swatinem/rust-cache@v2
      - name: Run cargo clippy
        uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: --workspace

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
      - uses: Swatinem/rust-cache@v2
      - name: Run cargo test
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --workspace

  build-scripts:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
      - uses: Swatinem/rust-cache@v2
      - name: Build build-scripts
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --package build-scripts
      - run: cp target/debug/build-scripts ./_build
      - uses: actions/upload-artifact@v3
        with:
          name: build-scripts
          path: _build
          if-no-files-found: error
          retention-days: 1

  version:
    runs-on: ubuntu-latest
    needs: [ build-scripts ]
    outputs:
      version: ${{ steps.getCirrusVersion.outputs.VERSION }}
      build-string: ${{ steps.getCirrusVersion.outputs.BUILD_STRING }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/download-artifact@v3
        with:
          name: build-scripts
      - run: chmod +x ./_build
      - name: Get cirrus version
        id: getCirrusVersion
        run: ./_build get-version >> "$GITHUB_OUTPUT"
      - name: Show version
        run: echo '`${{ steps.getCirrusVersion.outputs.VERSION }}` - `${{ steps.getCirrusVersion.outputs.BUILD_STRING }}`' > $GITHUB_STEP_SUMMARY

  package-windows:
    runs-on: ubuntu-latest
    needs:
      - build-scripts
      - version
    env:
      target: x86_64-pc-windows-gnu
    steps:
      - uses: actions/checkout@v3
      - uses: actions/download-artifact@v3
        with:
          name: build-scripts
      - run: chmod +x ./_build
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: ${{ env.target }}
          profile: minimal
      - uses: actions/setup-go@v3
        with:
          go-version: ${{ env.go-version }}
          cache: true
          cache-dependency-path: vendor/restic/go.sum
      - name: Install mingw cross compiler
        run: sudo apt-get update && sudo apt-get install -y gcc-mingw-w64-x86-64
      - uses: Swatinem/rust-cache@v2
      - name: Build package
        run: >
          ./_build package
          --version ${{ needs.version.outputs.version }}
          --build-string ${{ needs.version.outputs.build-string }}
          --target ${{ env.target }}
          --features bundled-restic-support
          --build-restic
      - uses: actions/upload-artifact@v3
        with:
          name: cirrus_${{ env.target }}
          path: public/*
          if-no-files-found: error
      - name: List archive contents
        run: |
          echo '```' > $GITHUB_STEP_SUMMARY
          tar tvf public/*.tar.xz >> $GITHUB_STEP_SUMMARY
          echo '```' >> $GITHUB_STEP_SUMMARY

  package-musl:
    runs-on: ubuntu-latest
    needs:
      - build-scripts
      - version
    strategy:
      fail-fast: true
      matrix:
        target:
          - x86_64-unknown-linux-musl
          - aarch64-unknown-linux-musl
    steps:
      - uses: actions/checkout@v3
      - uses: actions/download-artifact@v3
        with:
          name: build-scripts
      - run: chmod +x ./_build
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: ${{ matrix.target }}
          profile: minimal
      - uses: actions/setup-go@v3
        with:
          go-version: ${{env.go-version }}
          cache: true
          cache-dependency-path: vendor/restic/go.sum
      - name: Setup Zig
        uses: goto-bus-stop/setup-zig@v2
        with:
          version: ${{ env.zig-version }}
      - uses: Swatinem/rust-cache@v2
        with:
          key: ${{matrix.target }}
      - name: Build package
        run: >
          ./_build package
          --version ${{ needs.version.outputs.version }}
          --build-string ${{ needs.version.outputs.build-string }}
          --target ${{ matrix.target }}
          --features bundled-restic-support
          --build-restic
          --cargo-env-file build-scripts/cargo-zig-linux-musl.env
      - uses: actions/upload-artifact@v3
        with:
          name: cirrus_${{ matrix.target }}
          path: public/*
          if-no-files-found: error
      - name: List archive contents
        run: |
          echo '```' > $GITHUB_STEP_SUMMARY
          tar tvf public/*.tar.xz >> $GITHUB_STEP_SUMMARY
          echo '```' >> $GITHUB_STEP_SUMMARY 

  publish-container-image:
    if: ${{ github.event_name == 'push' }}
    needs:
      - build-scripts
      - version
      - package-musl
    uses: ./.github/workflows/publish-container-image.yml
    with:
      version: ${{ needs.version.outputs.version }}
      build-string: ${{ needs.version.outputs.build-string }}

  publish-package:
    if: ${{ github.event_name == 'push' }}
    needs:
      - version
      - package-musl
      - package-windows
    uses: ./.github/workflows/publish-package.yml
    with:
      version: ${{ needs.version.outputs.version }}
      build-string: ${{ needs.version.outputs.build-string }}
