name: Publish container image
on:
  workflow_call:
    inputs:
      version:
        description: cirrus main version
        required: true
        type: string
      build-string:
        description: cirrus build string
        required: true
        type: string

jobs:
  container-image:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        target:
          - x86_64-unknown-linux-gnu
          - armv7-unknown-linux-gnueabihf
          - aarch64-unknown-linux-gnu
        include:
          - target: x86_64-unknown-linux-gnu
            target_tag: linux-amd64
          - target: armv7-unknown-linux-gnueabihf
            target_tag: linux-arm32v7
          - target: aarch64-unknown-linux-gnu
            target_tag: linux-arm64v8
    env:
      tag: ghcr.io/${{ github.repository_owner }}/cirrus:${{ inputs.version }}-${{ inputs.build-string }}-${{ matrix.target_tag }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/download-artifact@v3
        with:
          name: build-scripts
          path: target
      - run: chmod +x target/build-scripts
      - uses: actions/download-artifact@v3
        with:
          name: cirrus_${{ matrix.target }}
      - uses: docker/setup-qemu-action@v2
      - name: Build container image
        run: >
          target/build-scripts container-image
          --binaries-tar cirrus_${{ matrix.target }}.tar.xz
          --tag ${{ env.tag }}
          --target ${{ matrix.target }}
      - uses: redhat-actions/podman-login@v1
        with:
          registry: ghcr.io/${{ github.repository_owner }}
          username: ${{ github.actor }}
          password: ${{ github.token }}
      - name: Push image
        uses: redhat-actions/push-to-registry@v2
        with:
          tags: ${{ env.tag }}

  manifest-list:
    runs-on: ubuntu-latest
    needs: [ container-image ]
    env:
      latest-tag: ghcr.io/${{ github.repository_owner }}/cirrus:latest
      versioned-tag: ghcr.io/${{ github.repository_owner }}/cirrus:${{ inputs.version }}-${{ inputs.build-string }}
    steps:
      - uses: redhat-actions/podman-login@v1
        with:
          registry: ghcr.io/${{ github.repository_owner }}
          username: ${{ github.actor }}
          password: ${{ github.token }}
      - name: Build manifest list
        run: >
          buildah manifest create manifest-list
          docker://${{ env.versioned-tag }}-linux-amd64
          docker://${{ env.versioned-tag }}-linux-arm32v7
          docker://${{ env.versioned-tag }}-linux-arm64v8
      - name: Push versioned manifest list
        run: buildah manifest push manifest-list docker://${{ env.versioned-tag }}
      - name: Push latest manifest list
        run: buildah manifest push manifest-list docker://${{ env.latest-tag }}
