name: Update restic
on:
  schedule:
    - cron: 0 6 * * SAT
  workflow_dispatch:

jobs:
  update-restic:
    runs-on: ubuntu-latest
    steps:
      - id: resticRelease
        uses: pozetroninc/github-action-get-latest-release@v0.5.0
        with:
          repository: restic/restic
          excludes: prerelease, draft
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
      - name: Set git author
        run: git config user.name "update-restic-workflow[bot]"
      - name: Update restic subtree
        uses: actions-rs/cargo@v1
        with:
          command: run
          args: >
            --package build-scripts -- 
            update-vendor --restic ${{ steps.resticRelease.outputs.release }}
      - uses: peter-evans/create-pull-request@v4
        with:
          branch: update-restic
          delete-branch: true
          title: Update restic to ${{ steps.resticRelease.outputs.release }}
          body: I'm automated beep boop
